"""Generate personalized CLAUDE.md rules from your own session data."""

from __future__ import annotations

from pathlib import Path

from tokenxray.colors import C
from tokenxray.commands.diagnose import _marathon_threshold
from tokenxray.display import fmt_cost
from tokenxray.parser import load_all_sessions

_HEADER = """\
# AI Coding Rules
# Generated by TokenXRay — based on your personal session data.
# Review and commit to your project root so Claude Code picks it up automatically.

"""

_FOOTER = """\
# --- General hygiene (always applies) ---
- Prefer partial file reads over loading entire files.
- Summarize search results; do not repeat large blocks of code verbatim.
- When asked to explore the codebase, report findings concisely then stop.
"""


def _build_rules(sessions: list) -> list[str]:
    if not sessions:
        return []

    total_cost = sum(s["cost"]["total"] for s in sessions)
    rules: list[str] = []

    # Marathon sessions → turn-limit rule with personalized threshold
    threshold = _marathon_threshold(sessions)
    remind_at = max(threshold // 2, 15)
    rules.append(
        f"# --- Session length ---\n"
        f"# Your data: sessions over {threshold} turns cost disproportionately more.\n"
        f"- When this conversation reaches {remind_at} turns, remind me to consider "
        f"starting a fresh session to contain context and cost.\n"
    )

    # Cache creation → context discipline
    total_cc = sum(s["cost"]["cache_create"] for s in sessions)
    cc_pct = total_cc / total_cost * 100 if total_cost > 0 else 0
    if cc_pct > 30:
        rules.append(
            f"# --- Context growth (cache creation is {cc_pct:.0f}% of your spend) ---\n"
            f"- Read only the sections of files you need; avoid loading entire large files.\n"
            f"- Summarize instead of quoting when referencing earlier content.\n"
        )

    # Token bombs → conciseness rule with personalized avg
    bomb_turns = []
    for s in sessions:
        bomb_turns.extend(t for t in s["turns"] if t["output"] > 3000)
    if bomb_turns:
        avg_output = sum(t["output"] for t in bomb_turns) / len(bomb_turns)
        rules.append(
            f"# --- Output length ({len(bomb_turns)} responses exceeded 3K tokens) ---\n"
            f"# Your avg bomb size: {avg_output:.0f} tokens.\n"
            f"- Default to concise responses. Aim for under 400 output tokens unless "
            f"the task genuinely requires more.\n"
            f"- Never pad responses with summaries, recaps, or explanations the user "
            f"didn't ask for.\n"
        )

    # Opus usage → model guidance
    opus_sessions = [s for s in sessions if any("opus" in m for m in s["models_used"])]
    if opus_sessions:
        opus_cost = sum(s["cost"]["total"] for s in opus_sessions)
        if opus_cost > 5:
            rules.append(
                f"# --- Model selection (Opus used in {len(opus_sessions)} sessions, "
                f"{fmt_cost(opus_cost)} spent) ---\n"
                f"- Use claude-sonnet for routine tasks: coding, file edits, searches.\n"
                f"- Reserve Opus only when deep multi-step reasoning is explicitly needed.\n"
            )

    # Subagent usage → direct-tool preference
    total_agent_calls = sum(
        sum(
            c
            for n, c in s.get("tool_calls", {}).items()
            if n.lower().startswith("agent")
        )
        for s in sessions
    )
    if total_agent_calls >= 10:
        rules.append(
            f"# --- Subagent usage ({total_agent_calls} Agent calls in your history) ---\n"
            f"- Prefer direct tools (Grep, Read, Glob) for simple lookups.\n"
            f"- Reserve Agent calls for tasks that genuinely benefit from isolation "
            f"or parallelism.\n"
        )

    return rules


def run(args) -> None:
    sessions = load_all_sessions(args.path, source_filter=getattr(args, "source", None))
    if not sessions:
        print(f"{C.RED}No sessions found.{C.RESET}")
        return

    rules = _build_rules(sessions)
    content = _HEADER + "\n".join(rules) + "\n" + _FOOTER

    dry_run = getattr(args, "rules_dry_run", False)
    if dry_run:
        print(content)
        return

    # Write to current directory, not the sessions directory
    claude_md = Path.cwd() / "CLAUDE.md"

    if claude_md.exists():
        existing = claude_md.read_text()
        marker = "# Generated by TokenXRay"
        if marker in existing:
            # Replace the generated block only
            start = existing.find(marker)
            # Find the block start — rewind to the previous blank line
            block_start = existing.rfind("\n\n", 0, start)
            block_start = block_start + 2 if block_start >= 0 else start
            new_content = existing[:block_start] + content
            claude_md.write_text(new_content)
            print(f"{C.GREEN}Updated generated rules in {claude_md}{C.RESET}")
        else:
            # Append to existing CLAUDE.md
            claude_md.write_text(existing.rstrip("\n") + "\n\n" + content)
            print(f"{C.GREEN}Appended generated rules to {claude_md}{C.RESET}")
    else:
        claude_md.write_text(content)
        print(f"{C.GREEN}Created {claude_md}{C.RESET}")

    print(f"{C.DIM}Commit this file so Claude Code picks it up automatically.{C.RESET}")
